server:
  port: 9999
spring:
  application:
    name: yy  #swagger页面好像没有作用？
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/beta_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: "123"
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
        # 监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: "000000"
flyway:
  locations: classpath:yys
  baseline-on-migrate: true